select * from USERINFO;

CREATE TABLE USERINFO.PERSON(
  PER_ID DECIMAL (5, 0) NOT NULL,
  PER_FIRST_NAME VARCHAR (40) NOT NULL,
  PER_LAST_NAME VARCHAR (40) NOT NULL,
  PER_BIRTH_DATE DATETIME ,
  PER_WEIGHT_KG DECIMAL (4, 2) NOT NULL,
  PER_HEIGHT_M DECIMAL (4, 2) NOT NULL,
  PRIMARY KEY (PER_ID)
);

CREATE TABLE USERINFO.ADDRESS(
  ADDR_ID DECIMAL (5, 0) NOT NULL ,
  STREET VARCHAR (40),
  HOUSE_NUMBER VARCHAR (40),
  PRIMARY KEY (PER_ID)
);


  select * from USERINFO.PERSON;
